apiVersion: apps/v1
kind: Deployment
metadata:
  name: healthcare-project
  labels:
    app: front-end
spec:
  replicas: 2
  selector: 
    matchLabels:
      app: healthcare
 template:
    metadata:
      labels:
        app: healthcare
    spec:
      containers:
        - name: healthcare
          image: swethamba859/healthcare:1.0 
          ports: 
           -containerPort: 8084
            name: http-web-app-01


---


apiVersion: v1
kind: Service
metadata:
  name: healthcare
spec:
  type: NodePort
  selector: 
    app: healthcare
  ports:
   - protocol: TCP
     port: 8084
     targetPort: http-web-app-01
