   
apiVersion: apps/v1
kind: Deployment
metadata:
  name: healthcare-deployment
  labels:
    app: healthcare-project
spec:
  replicas: 2
  selector:
    matchLabels:
      app: healthcare-project
  template:
    metadata:
      labels:
        app: healthcare-project
    spec:
      containers:
      - name: healthcare-project
        image: swethamba859/healthcare-project:1
        ports:
        - containerPort: 8084
        
        
---

apiVersion: v1
kind: Service
metadata:
  name: healthcare-service
spec:
  selector:
    app: healthcare-project
  type: NodePort
  ports:
    - protocol : TCP
      port: 8084
      targetPort: 8084
